# Generated by Django 2.1.7 on 2019-05-04 16:51

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='known',
            field=mdeditor.fields.MDTextField(default='', verbose_name='课程须知'),
        ),
    ]
