# Generated by Django 2.1.7 on 2019-05-04 17:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_known'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=200, verbose_name='课程公告')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='公告课程')),
            ],
            options={
                'verbose_name': '课程公告',
                'verbose_name_plural': '课程公告',
            },
        ),
        migrations.RemoveField(
            model_name='courseresource',
            name='add_time',
        ),
    ]
