# Generated by Django 2.1.7 on 2019-05-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20190504_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='视频内容'),
        ),
    ]
