# Generated by Django 2.1.7 on 2019-04-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='birth_day',
            new_name='birday',
        ),
    ]
